Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12"

    config.ssh.disable_deprecated_algorithms = true
    config.ssh.insert_key = false
    config.ssh.keys_only = false

    config.vm.provider "parallels" do |prl|
        prl.memory = "2048"
        prl.cpus = 4
        prl.name = "ibox"
        prl.update_guest_tools = true
        # prl.linked_clone = false
    end
    
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
