layer = "top"
position = "top"
height = 30

[[start]]
type = "custom"

[[start.bar]]
type = "button"
name = "os-icon"
label = "󱄅"
on_click = "!wleave"

[[start.bar]]
type = "clock"
name = "clock"
format = " %d/%m  %H:%M:%S%Z"

[[center]]
type = "music"
name = "music"
player_type = "mpris"
format = "{title} / {artist}"
truncate = "end"

[[end]]
type = "script"
name = "network"
cmd = "~/.config/ironbar/scripts/network.sh"

[[end]]
type = "bluetooth"
name = "bluetooth"

[[end]]
type = "volume"
name = "pulseaudio"
format = "{icon} {percentage}%"
mute_format = " Muted"
on_click_right = "pavucontrol"

[[end]]
type = "sys_info"
name = "temperature"
format = [ " {temp_c@thinkpad CPU}°C" ]

[[end]]
type = "sys_info"
name = "memory"
format = [ " {memory_percent}%" ]
on_click_left = "kitty --start-as=fullscreen --title btop sh -c 'btop'"

[[end]]
type = "script"
name = "battery"
cmd = "~/.config/ironbar/scripts/battery.sh"

[[end]]
type = "notifications"
name = "notifications"

[end.icons]
volume_high = ""
volume_medium = ""
volume_low = ""
muted = " Muted"

[end.interval]
temps = 5
memory = 30
