Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"

    config.vm.provider "parallels" do |vb|
        vb.memory = "4096"
        vb.cpus = 8
        vb.name = "dockerd-box"
    end
    
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yml"
    end
end
