Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"

    config.vm.provider "parallels" do |prl|
        prl.memory = "4096"
        prl.cpus = 8
        prl.name = "dockerd-box"
        prl.update_guest_tools = true
    end
    
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yml"
    end
end
