Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    
    msg = <<-MSG
    To run `docker` on the host (assumes docker-cli is installed), run the following commands:
    ------
    docker context create dockerd-box --docker "ssh://vagrant@dockerd-box"
    docker context use dockerd-box
    docker run --rm hello-world
    ------
    MSG

    config.vm.post_up_message = msg

    config.ssh.disable_deprecated_algorithms = true
    config.ssh.insert_key = false
    config.ssh.keys_only = false

    config.vm.provider "parallels" do |prl|
        prl.memory = "4096"
        prl.cpus = 8
        prl.name = "dockerd-box"
        prl.update_guest_tools = true
    end
    
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
